repos:
  - hooks:
      - id: black
        language_version: python3
        exclude: ^docs/tutorial-project/
    repo: https://github.com/ambv/black
    rev: 22.12.0
  - hooks:
      - id: isort
        language_version: python3
        exclude: ^docs/tutorial-project/
    repo: https://github.com/PyCQA/isort
    rev: 5.12.0
  - hooks:
      - id: flake8
        language_version: python3
        exclude: ^docs/tutorial-project/
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-docstrings
          - flake8-string-format
    repo: https://github.com/pycqa/flake8
    rev: 4.0.1
